### ISSUE TITLE
Binary

### ISSUE THREAD

**Issue by JasonJAyalaP** [lihaoyi/XMLite#1]
Any chance of getting a compiled binary release for users who want to try it but don't have a scala environment?

**Comment by lihaoyi** [comment]
Probably not, I'm afraid, for a few reasons:
- It's not done yet; lots of syntax still is not well defined, despite the pile of unit tests
- its tied to the Scala std lib because it uses parser combinators. That means you'll need to pull down the bulk of the Scala distribution anyway.

Maybe in the future when it's more complete, but for now it's more a curiosity than a production-ready library
